.\"/* 
.\" * All rights reserved
.\" * Copyright (c) 2015-2017 SUSE LINUX GmbH, Nuernberg, Germany.
.\" * Authors: Howard Guo
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\" 
.TH sapconf 8 "December 2017" "util-linux" "System Administration"
.SH NAME
sapconf \- Kernel and system configuration for SAP products

.SH SYNOPSIS
sapconf ACTION_NAME

.SH DESCRIPTION
sapconf activates SAP Netweaver, SAP ASE/Sybase, SAP Business OBJects (BOBJ) or HANA/BusinessOne tuning profiles depending on the command line action input. sapconf is deprecated in favour of tune daemon (tuned) and its profiles "sap-netweaver", "sap-hana", "sap-ase", "sap-bobj".

.SH ACTIONS

.IP \[bu]
start,restart,try-restart,reload - If the tune daemon does not have any profile active, activiate SAP Netweaver tuning profile. Otherwise leave the profile choice alone and activate tune daemon.

.IP \[bu]
netweaver - Activate SAP Netweaver tuning profile. Exit 1 on failure.

.IP \[bu]
hana,b1 - Activate SAP HANA or BusinessOne tuning profile. Exit 1 on failure.

.IP \[bu]
ase,sybase - Activate SAP ASE (Sybase) tuning profile. Exit 1 on failure.

.IP \[bu]
bobj - Activate SAP Business OBJects (BOBJ) tuning profile. Exit 1 on failure.

.IP \[bu]
stop - Do nothing.

.IP \[bu]
status - Report the status of tune daemon. Exit 1 on failure.

.SH SEE\ ALSO
tuned-profiles-sap-hana(7), tuned-profiles-sap-netweaver(7), tuned-profiles-sap-ase(7), tuned-profiles-sap-bobj(7)

.SH AUTHORS
.na
Werner Fink, Fabian Herschel, Howard Guo, Angela Briel
.nf
