.\"/* 
.\" * All rights reserved
.\" * Copyright (c) 2015-2020 SUSE LLC
.\" * Authors: Howard Guo
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\" 
.TH sapconf 7 "March 2020" "util-linux" "System Administration"
.SH NAME
sapconf \- Kernel and system configuration for SAP products

.SH DESCRIPTION
sapconf automatically optimises kernel parameters and system configuration for running SAP workloads like NetWeaver, Sybase/ASE, BOBJ and HANA and Business One softwares.
.br
sapconf is \fBno longer\fP working on top of the tune daemon.

.SH CONFIGURATION
The main customization can be done in the central configuration file \fI/etc/sysconfig/sapconf\fP of sapconf.
.br
All parameters to be set by sapconf are descibed in detail within this file and will be read from this file.
.br
Be in mind: Higher or lower system values set by the system, the SAP installer or by the administrator using sysctl command or sysctl configuration files will be overwritten by sapconf, if they are part of the sapconf sysconfig file.
.br
During the package update of sapconf existing former custom tuned profiles related to sapconf in \fI/etc/tuned\fP are preserved in \fI/var/lib/sapconf/saved_configs\fP. Changed parameter values from an existing sapconf or sap-hana or sap-netweaver profile are automatically added to \fI/etc/sysconfig/sapconf\fP.
.PP
The process is splitted in 2 scripts. The \fIcommon.sh\fP is inherited by the script \fIsapconf\fP which will do the whole tuning.
.PP
Every tuning action is logged to \fI/var/log/sapconf.log\fP

.SH PARAMETER
To get a better base in the future for mixed HANA and ABAB workloads on one system, sapconf will use the same tuning values for HANA, Sybase/ASE, BOBJ and NetWeaver workloads.
.br
The following parameters are calculated and tuned, according to various SAP notes and best practices:
.IP \[bu]
Shared memory: kernel.shmall, kernel.shmmax, kernel.shmmni
.IP \[bu]
Size of tmpfs
.IP \[bu]
Maximum number of memory mapping regions: vm.max_map_count
.IP \[bu]
Maximum number of open file descriptors in /etc/security/limits.conf
.IP \[bu]
Dirty memory: Set vm.dirty_bytes and vm.dirty_background_bytes
.IP \[bu]
Disable TCP slow start on idle connections: net.ipv4.tcp_slow_start_after_idle
.IP \[bu]
Turn off KSM: /sys/kernel/mm/ksm
.IP \[bu]
Turn off NUMA-balancing: kernel.numa_balancing
.IP \[bu]
Disable transparent_hugepage
.IP \[bu]
CPU power management and disk cache
.IP \[bu]
Enable uuidd.socket.

.SH "SAP NOTES"
All settings are done according to SAP note number 900929, 941735, 1771258, 1980196, 2578899, 2031375, 2131662, 2684254, 2382421 and 2534844
.br
See the comments in the central sapconf configuration file \fI/etc/sysconfig/sapconf\fR or \fBsapconf(5)\fP for details.

.SH ACTIVATION
To activate the sapconf tuning, run as root:
.PP
systemctl start sapconf.service
.PP
Make sure that the sapconf service is enabled and running.
.br
This is normally done automatically after the sapconf package installation.
.PP
Check
.br
systemctl status sapconf.service
.PP
Enable
.br
systemctl enabled sapconf.service
.PP
Start
.br
systemctl start sapconf.service

If the start of the sapconf.service failed, use the command '\fBsystemctl status sapconf -l\fR' to get detailed information about the failure.

.SH "PACKAGE REQUIREMENTS"
The following package requirements exist for the sapconf package:
.TP 4
.BI "sysstat" 
service is started after package installation (see SAP Note 2578899)
.PP
.TP 4
.BI "uuidd.socket"
service is enabled and started after package installation (see SAP Note 2578899)
.PP
Note: These settings will be applied during the post stage of the sapconf package installation.
.PP
Note: If the package sapconf is removed from the system, the following settings will still remain:
.TP 4
.BI "Maximum number of open file descriptors in /etc/security/limits.conf"
Please remove the entries manually, if they are not needed any longer.
.PP
.TP 4
.BI "A running sysstat service."
Please stop the sysstat service manually, if it is not needed any longer.
.PP
.TP 4
.BI /etc/sysconfig/sapconf
The central configuration file of sapconf is not removed during package removal.
.PP
.TP 4
.BI /var/lib/sapconf/saved_configs
Private copies of sapconf related tuned profiles moved from /etc/tuned during the package update are not removed during package removal.
.PP
.TP 4
.BI /var/log/sapconf.log
The log file of sapconf will not be removed during package removal.
.PP

.SH "FILES"
.PP
\fI/etc/sysconfig/sapconf\fR
.RS 4
the central configuration file
.br
Here you can find all parameters, wich are affected by sapconf. The actual setting value, the source SAP Note, a short explanation and where this parameter is set.
.br
If you change parameter values please don't forget to reload sapconf service to get the changes take effect.
.PP
The package installation of sapconf will have regard for changes made to /etc/sysconfig/sapconf. In some cases the old configuration file is preserved as /etc/sysconfig/sapconf.rpmsave and the new sapconf sysconfig file is copied to /etc/sysconfig/sapconf. Please make sure that you merge needed changes from this file to the new /etc/sysconfig/sapconf file before you restart the sapconf service.
.RE
.PP
\fI/var/log/sapconf\.log\fR
.RS 4
log file of sapconf
.RE
.PP
\fI/var/lib/sapconf/saved_state/\fR
.RS 4
sapconf was designed to preserve the state of the system before starting the SAP specific tuning, so that it will be possible to restore this previous state of the system, if the SAP specific tuning is no longer needed or should be changed.

This system state is saved during the 'start' of the sapconf service in the sapconf internal used files in /var/lib/sapconf/saved_state. The content of these files highly depends on the previous state of the system.
.br
If the system was tuned by sapconf, no further monitoring of the system parameters are done, so changes of sapconf relevant parameters will not be observed. If the sapconf service is stopped, then first the values read from the /var/lib/sapconf/saved_state files will be set to the system to restore the previous system state and then the corresponding saved_state file will be removed.

Please do not change or remove files in this directory. The knowledge about the previous system state gets lost and the stop functionality of the sapconf service will be destructed. So you will lose the capability to revert back the tunings sapconf has done.
.RE
.PP
\fI/var/lib/sapconf/saved_configs/\fR
.RS 4
Private copies of sapconf related tuned profiles moved from /etc/tuned during the package update can be found here, if these profile directories were available during the package update. So it's possible to check, if there are custom specific tuning values missing in the current configuration in \fI/etc/sysconfig/sapconf\fR
.RE

.SH SEE\ ALSO
.BR sapconf (5)

.SH AUTHORS
.na
Howard Guo, Angela Briel
.nf
