.\"/* 
.\" * All rights reserved
.\" * Copyright (c) 2015 SUSE LINUX GmbH, Nuernberg, Germany.
.\" * Authors: Howard Guo
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\" 
.TH SAPConf 8 "February 2014" "util-linux" "System Administration"
.SH NAME
SAPConf \- Kernel and system configuration for SAP products

.SH SYNOPSIS
.BR "SAPconf" 
.SH DESCRIPTION
.ad
.fi
\fISAPConf\fP is a backward-compatiblility script to start the 
script sapconf which really does the work. SAPConf is only 
provided for customers, who used that script in the past.

.SH ARGUMENTS

.SH FILES
.na
.nf
.SH BUGS
.ad
.fi
.SH AUTHOR(S)
.na
Werner Fink, Fabian Herschel
.nf
