.\"/* 
.\" * All rights reserved
.\" * Copyright (c) 2016, 2017 SUSE LLC
.\" * Authors: Howard Guo <hguo@suse.com>
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\" 
.TH TUNED_PROFILES_SAPCONF "7" "August 2018" "Adaptive system tuning daemon" "tuned"
.SH NAME
tuned\-profiles\-sapconf - Tuning profile for SAP workloads.

.SH DESCRIPTION
The tuning profile automatically optimises kernel parameters and system configuration for running SAP workloads like NetWeaver, Sybase/ASE, BOBJ and HANA and Business One softwares.

The following parameters are calculated and tuned, according to various SAP notes and best practices:
.IP \[bu]
Shared memory: kernel.shmall, kernel.shmmax, kernel.shmmni
.IP \[bu]
Size of tmpfs
.IP \[bu]
Maximum number of memory mapping regions: vm.max_map_count
.IP \[bu]
Maximum number of open file descriptors in /etc/security/limits.conf
.IP \[bu]
Dirty memory: Set vm.dirty_bytes and vm.dirty_background_bytes
.IP \[bu]
Disable TCP slow start on idle connections: net.ipv4.tcp_slow_start_after_idle
.IP \[bu]
Turn off KSM: /sys/kernel/mm/ksm
.IP \[bu]
Turn off NUMA-balancing: kernel.numa_balancing
.IP \[bu]
Disable transparent_hugepage
.IP \[bu]
CPU power management and disk cache
.IP \[bu]
Enable uuidd.socket.

Note that the former profiles
.BR sap-netweaver 
.BR sap-hana
.BR sap-ase and
.BR sap-bobj
now are consolidated to one base sapconf profile to get a better base in the future for mixed HANA and ABAB workloads on one system.

.SH "SAP NOTES"
The tuned parameters are calculated according to SAP note number 900929, 941735, 1771258, 1980196, 2578899, 2031375, 2055470, 2131662, 2684254, 2382421 and 2534844
.br See the comments in the central sapconf configuration file \fI/etc/sysconfig/sapconf\fR for details.

.SH ACTIVATION
To activate the sapconf tuning profile, run as root:

tuned-adm profile sapconf

.SH "FILES"
.PP
\fI/etc/sysconfig/sapconf\fR
.RS 4
the central configuration file
.RE
.PP
\fI/usr/lib/tuned/sapconf/tuned.conf\fR
.RS 4
the sapconf profile special configuration file.
.RE

.SH "SEE ALSO"
.BR sapconf (5)
.BR sapconf (7)
.BR tuned (8)
.BR tuned\-adm (8)
.SH AUTHOR
.NF
Howard Guo, Angela Briel
