name: shellcheck

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master and sle-12 branch
  pull_request:
    branches: [ master, sle-12 ]

jobs:
  # This workflow contains a single job called "shellcheck"
  shellcheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Checks scripts with Shellcheck
        shell: bash
        run: |
          echo "Running Shellcheck..."
          find . -type f -exec awk ' /^#!.*bash/{print FILENAME} {nextfile}' {} + | xargs shellcheck -s bash && echo "Everything is OK!"
